### ISSUE TITLE
Need some help please

### ISSUE THREAD

**Issue by tickers** [absalon-james/usage#3]
Running on an older IceHouse release I am getting these errors, works fine on my Mitaka release
 usage-report 
Traceback (most recent call last):
  File "/usr/bin/usage-report", line 9, in <module>
    load_entry_point('usage', 'console_scripts', 'usage-report')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/**init**.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/**init**.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/**init**.py", line 2241, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/root/usage/usage/console.py", line 8, in <module>
    from clients import ClientManager
  File "/root/usage/usage/clients.py", line 7, in <module>
    from keystoneauth1 import loading
  File "/usr/lib/python2.6/site-packages/keystoneauth1/loading/**init**.py", line 13, in <module>
    from keystoneauth1.loading.base import \*  # noqa
  File "/usr/lib/python2.6/site-packages/keystoneauth1/loading/base.py", line 16, in <module>
    import stevedore
  File "/usr/lib/python2.6/site-packages/stevedore/**init**.py", line 23, in <module>
    LOG.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'

 python -V
Python 2.6.6
rhel 6.6 server

**Comment by absalon-james** [comment]
You may be out of luck with this one.

I do not think stevedore supports python2.6. 
[https://bugs.launchpad.net/python-stevedore/+bug/1546370](https://bugs.launchpad.net/python-stevedore/+bug/1546370)
